-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin_thanks_clicks
(
    chat_id bigint NOT NULL,
    message_id integer NOT NULL,
    user_id bigint NOT NULL,
    author text COLLATE pg_catalog."default" NOT NULL,
    item_id bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_thanks_clicks_pkey PRIMARY KEY (chat_id, message_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.admin_thanks_totals
(
    author text COLLATE pg_catalog."default" NOT NULL,
    thanks_total bigint NOT NULL DEFAULT 0,
    users_total bigint NOT NULL DEFAULT 0,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_thanks_totals_pkey PRIMARY KEY (author)
);

CREATE TABLE IF NOT EXISTS public.admin_thanks_users
(
    author text COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    thanks_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT admin_thanks_users_pkey PRIMARY KEY (author, user_id)
);

CREATE TABLE IF NOT EXISTS public.admins
(
    user_id bigint NOT NULL,
    username text COLLATE pg_catalog."default",
    added_by bigint,
    added_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admins_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.auction_manual_results
(
    auction_id integer NOT NULL,
    winner_user_id bigint,
    winner_username text COLLATE pg_catalog."default",
    owner_user_id bigint,
    owner_username text COLLATE pg_catalog."default",
    amount integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    CONSTRAINT auction_manual_results_pkey PRIMARY KEY (auction_id)
);

CREATE TABLE IF NOT EXISTS public.auction_owners
(
    id serial NOT NULL,
    auction_id integer NOT NULL,
    user_id bigint NOT NULL,
    folder text COLLATE pg_catalog."default" NOT NULL DEFAULT 'default'::text,
    owner_folder text COLLATE pg_catalog."default" NOT NULL DEFAULT 'default'::text,
    CONSTRAINT auction_owners_pkey PRIMARY KEY (id),
    CONSTRAINT ux_auction_owners UNIQUE (auction_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.auction_posts_backfill
(
    post_id bigint NOT NULL,
    post_link text COLLATE pg_catalog."default" NOT NULL,
    post_date_msk timestamp without time zone,
    end_time_msk timestamp without time zone,
    deadline_msk timestamp without time zone,
    root_id bigint,
    discussion_id bigint,
    msgs_scanned integer NOT NULL DEFAULT 0,
    numeric_msgs integer NOT NULL DEFAULT 0,
    thread_bids integer NOT NULL DEFAULT 0,
    thread_valid integer NOT NULL DEFAULT 0,
    max_thread_valid bigint,
    winner_id bigint,
    any_valid integer NOT NULL DEFAULT 0,
    max_any_valid bigint,
    note text COLLATE pg_catalog."default",
    CONSTRAINT auction_posts_backfill_pkey PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS public.auction_posts_stats
(
    post_id bigint NOT NULL,
    checked boolean NOT NULL DEFAULT false,
    checked_by bigint,
    checked_at timestamp without time zone,
    manual_winner_id bigint,
    manual_max_bid bigint,
    manual_valid_bids integer,
    manual_total_bids integer,
    manual_note text COLLATE pg_catalog."default",
    excluded boolean NOT NULL DEFAULT false,
    excluded_by bigint,
    excluded_at timestamp without time zone,
    excluded_reason text COLLATE pg_catalog."default",
    ordinal_no integer,
    manual_date date,
    manual_time time without time zone,
    deck_no integer,
    card_title text COLLATE pg_catalog."default",
    bidders_count integer,
    min_bid bigint,
    max_bid bigint,
    owner_id bigint,
    manual_link text COLLATE pg_catalog."default",
    CONSTRAINT auction_posts_stats_pkey PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS public.auction_win_mailings
(
    id bigserial NOT NULL,
    auction_id integer NOT NULL,
    target text COLLATE pg_catalog."default" NOT NULL,
    sent_by_user_id bigint,
    sent_by_username text COLLATE pg_catalog."default",
    sent_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auction_win_mailings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auctions
(
    auction_id serial NOT NULL,
    card_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hero_name character varying(255) COLLATE pg_catalog."default",
    image_id text COLLATE pg_catalog."default",
    start_price integer NOT NULL DEFAULT 0,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'scheduled'::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    currency character varying(20) COLLATE pg_catalog."default" DEFAULT 'чашки'::character varying,
    comment text COLLATE pg_catalog."default",
    message_id bigint,
    notified_start boolean DEFAULT false,
    notified_1min boolean DEFAULT false,
    notified_end boolean DEFAULT false,
    proof_photo_id text COLLATE pg_catalog."default",
    discussion_message_id bigint,
    notified_card_subs boolean DEFAULT false,
    auction_kind character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'standard'::character varying,
    craft_uid_possible boolean,
    card_id integer,
    finalization_started_at timestamp with time zone,
    finalization_finished_at timestamp with time zone,
    finalization_attempts integer NOT NULL DEFAULT 0,
    finalization_error text,
    publication_started_at timestamp with time zone,
    publication_finished_at timestamp with time zone,
    publication_next_attempt_at timestamp with time zone,
    publication_attempts integer NOT NULL DEFAULT 0,
    publication_error text,
    CONSTRAINT chk_auctions_status CHECK (status::text = ANY (ARRAY[
        'draft', 'moderation', 'pending', 'approved', 'scheduled',
        'publishing', 'publication_failed', 'active', 'finalizing',
        'finalization_failed', 'finished', 'rejected', 'cancelled', 'closed'
    ]::text[])),
    CONSTRAINT chk_auctions_currency CHECK (currency::text = ANY (ARRAY[
        'алмазы', 'чашки', 'сокровища'
    ]::text[])),
    CONSTRAINT auctions_auction_kind_chk CHECK (auction_kind::text = ANY (ARRAY[
        'standard', 'reverse', 'fast', 'free', 'black', 'exchange'
    ]::text[])),
    CONSTRAINT chk_auctions_time_order CHECK (
        status::text <> ALL (ARRAY[
            'scheduled', 'publishing', 'publication_failed', 'active',
            'finalizing', 'finalization_failed', 'finished'
        ]::text[])
        OR end_time > start_time
    ),
    CONSTRAINT auctions_pkey PRIMARY KEY (auction_id)
);

CREATE TABLE IF NOT EXISTS public.auctions_image_id_backup
(
    auction_id integer NOT NULL,
    old_image_id text COLLATE pg_catalog."default",
    backed_up_at timestamp without time zone DEFAULT now(),
    CONSTRAINT auctions_image_id_backup_pkey PRIMARY KEY (auction_id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id serial NOT NULL,
    user_id bigint,
    action_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    auction_id bigint,
    details text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.autobid_actions
(
    action_id serial NOT NULL,
    autobid_id integer NOT NULL,
    auction_id integer NOT NULL,
    target_user_id bigint NOT NULL,
    amount integer NOT NULL,
    discussion_message_id bigint NOT NULL,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT autobid_actions_pkey PRIMARY KEY (action_id),
    CONSTRAINT autobid_actions_discussion_message_id_key UNIQUE (discussion_message_id)
);

CREATE TABLE IF NOT EXISTS public.autobids
(
    autobid_id serial NOT NULL,
    auction_id integer NOT NULL,
    target_user_id bigint NOT NULL,
    target_username text COLLATE pg_catalog."default",
    max_amount integer NOT NULL,
    step integer NOT NULL DEFAULT 10,
    is_active boolean NOT NULL DEFAULT true,
    created_by bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT autobids_pkey PRIMARY KEY (autobid_id),
    CONSTRAINT autobids_auction_user_uniq UNIQUE (auction_id, target_user_id)
);

CREATE TABLE IF NOT EXISTS public.bids
(
    bid_id serial NOT NULL,
    auction_id integer NOT NULL,
    bidder_id bigint NOT NULL,
    amount integer NOT NULL,
    placed_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    discussion_message_id bigint,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT bids_pkey PRIMARY KEY (bid_id)
);

CREATE TABLE IF NOT EXISTS public.card_day_notifications
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    card_id bigint NOT NULL,
    day date NOT NULL,
    sent_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT card_day_notifications_pkey PRIMARY KEY (id),
    CONSTRAINT card_day_notifications_user_id_card_id_day_key UNIQUE (user_id, card_id, day)
);

CREATE TABLE IF NOT EXISTS public.cards
(
    card_id serial NOT NULL,
    deck_id integer NOT NULL,
    num integer NOT NULL,
    hero_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    image_id text COLLATE pg_catalog."default",
    rarity character varying(50) COLLATE pg_catalog."default" NOT NULL,
    story character varying(255) COLLATE pg_catalog."default" NOT NULL,
    quote text COLLATE pg_catalog."default",
    card_name character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    obtain_type obtain_type NOT NULL DEFAULT 'diamonds'::obtain_type,
    obtain_amount integer NOT NULL DEFAULT 0,
    media_type text COLLATE pg_catalog."default" NOT NULL DEFAULT 'photo'::text,
    media_file_id text COLLATE pg_catalog."default",
    media_unique_id text COLLATE pg_catalog."default",
    thumb_file_id text COLLATE pg_catalog."default",
    CONSTRAINT cards_pkey PRIMARY KEY (card_id)
);

CREATE TABLE IF NOT EXISTS public.custom_emojis
(
    name text COLLATE pg_catalog."default" NOT NULL,
    emoji_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT custom_emojis_pkey PRIMARY KEY (name),
    CONSTRAINT custom_emojis_emoji_id_key UNIQUE (emoji_id)
);

CREATE TABLE IF NOT EXISTS public.decks
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    deck_type deck_type DEFAULT 'resource'::deck_type,
    CONSTRAINT decks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.delete_requests
(
    id serial NOT NULL,
    lot_id integer NOT NULL,
    user_id bigint NOT NULL,
    reason text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    CONSTRAINT delete_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exchange_batches
(
    batch_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    deck_id integer NOT NULL,
    mode text COLLATE pg_catalog."default" NOT NULL,
    currency text COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    proof_photo_id text COLLATE pg_catalog."default" NOT NULL DEFAULT 'NO_PROOF'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    moderator_id bigint,
    moderator_username text COLLATE pg_catalog."default",
    moderator_comment text COLLATE pg_catalog."default",
    moderated_at timestamp with time zone,
    moderated_by bigint,
    moderated_username text COLLATE pg_catalog."default",
    moderated_comment text COLLATE pg_catalog."default",
    manual_winner_id bigint,
    manual_winner_username text COLLATE pg_catalog."default",
    manual_price integer,
    manual_link text COLLATE pg_catalog."default",
    manual_set_by bigint,
    manual_set_at timestamp with time zone,
    manual_sent_at timestamp with time zone,
    posted_chat_id bigint,
    posted_message_id bigint,
    posted_at timestamp with time zone,
    publication_started_at timestamp with time zone,
    publication_finished_at timestamp with time zone,
    publication_error text,
    deleted_at timestamp with time zone,
    CONSTRAINT chk_exchange_batches_status CHECK (status = ANY (ARRAY[
        'pending', 'approved', 'rejected', 'publishing',
        'publication_failed', 'published', 'deleted'
    ]::text[])),
    CONSTRAINT exchange_batches_pkey PRIMARY KEY (batch_id)
);

CREATE TABLE IF NOT EXISTS public.exchange_items
(
    item_id bigserial NOT NULL,
    batch_id bigint NOT NULL,
    card_id integer,
    card_name text COLLATE pg_catalog."default",
    hero_name text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT exchange_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.exchange_print_stats
(
    batch_id integer NOT NULL,
    manual_winner_id bigint,
    manual_winner_name text COLLATE pg_catalog."default",
    manual_price integer,
    manual_link text COLLATE pg_catalog."default",
    updated_by bigint,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT exchange_print_stats_pkey PRIMARY KEY (batch_id)
);

CREATE TABLE IF NOT EXISTS public.guides_thanks
(
    user_id bigint NOT NULL,
    thanks_count integer NOT NULL DEFAULT 0,
    last_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT guides_thanks_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.market_listing_items
(
    id serial NOT NULL,
    listing_id integer NOT NULL,
    card_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    proof_file_id text COLLATE pg_catalog."default",
    CONSTRAINT market_listing_items_pkey PRIMARY KEY (id),
    CONSTRAINT ux_mli UNIQUE (listing_id, card_id)
);

CREATE TABLE IF NOT EXISTS public.market_listings
(
    listing_id serial NOT NULL,
    seller_id bigint NOT NULL,
    status listing_status NOT NULL DEFAULT 'active'::listing_status,
    description text COLLATE pg_catalog."default",
    currency_type market_currency NOT NULL DEFAULT 'cash'::market_currency,
    cash_code character varying(8) COLLATE pg_catalog."default",
    price_num numeric(14, 2) NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    offer_kind offer_kind NOT NULL DEFAULT 'cards'::offer_kind,
    cover_file_id text COLLATE pg_catalog."default",
    channel_id bigint,
    message_id bigint,
    deck_id integer,
    proof_file_id text COLLATE pg_catalog."default",
    proof_by_card jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT market_listings_pkey PRIMARY KEY (listing_id)
);

CREATE TABLE IF NOT EXISTS public.market_rate_tiers
(
    id serial NOT NULL,
    listing_id integer NOT NULL,
    label text COLLATE pg_catalog."default",
    qty integer,
    pay_type market_currency NOT NULL,
    cash_code character varying(8) COLLATE pg_catalog."default",
    price numeric(14, 2) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    CONSTRAINT market_rate_tiers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    notification_id serial NOT NULL,
    user_id bigint NOT NULL,
    auction_id integer NOT NULL,
    notification_type character varying(50) COLLATE pg_catalog."default",
    sent_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS public.preset_aliases
(
    preset_id bigint NOT NULL,
    alias text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT preset_aliases_pkey PRIMARY KEY (preset_id, alias)
);

CREATE TABLE IF NOT EXISTS public.presets
(
    id bigserial NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT presets_pkey PRIMARY KEY (id),
    CONSTRAINT presets_key_key UNIQUE (key)
);

CREATE TABLE IF NOT EXISTS public.settings
(
    user_id bigint NOT NULL,
    notify_auction_start boolean DEFAULT true,
    notify_bid_reminder boolean DEFAULT true,
    notify_auction_end boolean DEFAULT true,
    notify_daily_today boolean DEFAULT false,
    CONSTRAINT settings_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.trusted_usernames
(
    username character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT trusted_usernames_pkey PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS public.uid_bans
(
    uid text COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    banned_by bigint,
    banned_at timestamp with time zone NOT NULL DEFAULT now(),
    banned_until timestamp with time zone,
    CONSTRAINT uid_bans_pkey PRIMARY KEY (uid)
);

CREATE TABLE IF NOT EXISTS public.uid_verification_confirmation_reminders
(
    conf_id bigint NOT NULL,
    stage_h integer NOT NULL,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uid_verification_confirmation_reminders_pkey PRIMARY KEY (conf_id, stage_h)
);

CREATE TABLE IF NOT EXISTS public.uid_verification_confirmations
(
    id bigserial NOT NULL,
    request_id bigint NOT NULL,
    counterparty_user_id bigint,
    counterparty_username text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    decided_at timestamp with time zone,
    message_chat_id bigint,
    message_id bigint,
    CONSTRAINT uid_verification_confirmations_pkey PRIMARY KEY (id),
    CONSTRAINT ux_uid_verif_conf_req_username UNIQUE (request_id, counterparty_username)
);

CREATE TABLE IF NOT EXISTS public.uid_verification_events
(
    id bigserial NOT NULL,
    request_id bigint NOT NULL,
    actor_id bigint,
    actor_username text COLLATE pg_catalog."default",
    event_type text COLLATE pg_catalog."default" NOT NULL,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uid_verification_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.uid_verification_requests
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    uid text COLLATE pg_catalog."default" NOT NULL,
    challenge_code text COLLATE pg_catalog."default" NOT NULL,
    profile_file_id text COLLATE pg_catalog."default" NOT NULL,
    deal_file_ids text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    decided_at timestamp with time zone,
    decided_by bigint,
    admin_comment text COLLATE pg_catalog."default",
    uid_proof_file_id text COLLATE pg_catalog."default",
    profile_proof_file_id text COLLATE pg_catalog."default",
    verification_code text COLLATE pg_catalog."default" NOT NULL,
    counterparty_usernames text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    reg_date_proof_file_id text COLLATE pg_catalog."default",
    extra_proof_file_ids text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    revision_flags text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    revision_reason text COLLATE pg_catalog."default",
    revision_requested_at timestamp with time zone,
    revision_by bigint,
    revision_by_username text COLLATE pg_catalog."default",
    revision_at timestamp with time zone,
    revision_returned_at timestamp with time zone,
    revision_completed_at timestamp with time zone,
    CONSTRAINT uid_verification_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.unreachable_users
(
    user_id bigint NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    last_seen timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT unreachable_users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_appeals
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    username text COLLATE pg_catalog."default",
    topic text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    participants text COLLATE pg_catalog."default",
    media_message_ids integer[] DEFAULT '{}'::integer[],
    origin_chat_id bigint NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    moderator_id bigint,
    moderator_username text COLLATE pg_catalog."default",
    moderator_comment text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_appeals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_bans
(
    id serial NOT NULL,
    user_id bigint NOT NULL,
    banned_until timestamp without time zone,
    reason character varying(255) COLLATE pg_catalog."default",
    issued_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_bans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_preset_subscriptions
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    preset_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_preset_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT user_preset_subscriptions_user_id_preset_id_key UNIQUE (user_id, preset_id)
);

CREATE TABLE IF NOT EXISTS public.user_subscriptions
(
    id serial NOT NULL,
    user_id bigint NOT NULL,
    card_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_confirmed_at timestamp with time zone,
    CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT ux_user_subscriptions UNIQUE (user_id, card_id)
);

CREATE TABLE IF NOT EXISTS public.user_uids
(
    uid text COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'verified'::text,
    verified_at timestamp with time zone NOT NULL DEFAULT now(),
    verified_by bigint,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_uids_pkey PRIMARY KEY (uid),
    CONSTRAINT user_uids_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_warnings
(
    id serial NOT NULL,
    user_id bigint NOT NULL,
    reason character varying(255) COLLATE pg_catalog."default",
    issued_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    details text COLLATE pg_catalog."default",
    CONSTRAINT user_warnings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL,
    username character varying(32) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    is_subscribed boolean DEFAULT true,
    is_luxury boolean DEFAULT false,
    warnings_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_trusted boolean DEFAULT false,
    pm_opened boolean DEFAULT false,
    first_pm_at timestamp without time zone,
    last_pm_at timestamp without time zone,
    uid_verif_confirmed_count integer NOT NULL DEFAULT 0,
    uid_verif_rejected_count integer NOT NULL DEFAULT 0,
    uid_verif_last_confirmed_at timestamp with time zone,
    uid_verif_last_rejected_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.admins
    ADD CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS admins_pkey
    ON public.admins(user_id);


ALTER TABLE IF EXISTS public.auction_owners
    ADD CONSTRAINT auction_owners_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_auction_owners_auction_id
    ON public.auction_owners(auction_id);


ALTER TABLE IF EXISTS public.auction_owners
    ADD CONSTRAINT auction_owners_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_auction_owners_user_id
    ON public.auction_owners(user_id);


ALTER TABLE IF EXISTS public.auction_posts_stats
    ADD CONSTRAINT auction_posts_stats_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.auction_posts_backfill (post_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS auction_posts_stats_pkey
    ON public.auction_posts_stats(post_id);


ALTER TABLE IF EXISTS public.auctions
    ADD CONSTRAINT auctions_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_auctions_card_id
    ON public.auctions(card_id);


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT fk_audit_auction FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT fk_audit_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.autobid_actions
    ADD CONSTRAINT autobid_actions_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS autobid_actions_auction_id_idx
    ON public.autobid_actions(auction_id);


ALTER TABLE IF EXISTS public.autobid_actions
    ADD CONSTRAINT autobid_actions_autobid_id_fkey FOREIGN KEY (autobid_id)
    REFERENCES public.autobids (autobid_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.autobids
    ADD CONSTRAINT autobids_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bids_auction
    ON public.bids(auction_id);


ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_bidder_id_fkey FOREIGN KEY (bidder_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bids_bidder
    ON public.bids(bidder_id);


ALTER TABLE IF EXISTS public.cards
    ADD CONSTRAINT cards_deck_id_fkey FOREIGN KEY (deck_id)
    REFERENCES public.decks (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE IF EXISTS public.delete_requests
    ADD CONSTRAINT delete_requests_lot_id_fkey FOREIGN KEY (lot_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.delete_requests
    ADD CONSTRAINT delete_requests_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.exchange_batches
    ADD CONSTRAINT exchange_batches_deck_id_fkey FOREIGN KEY (deck_id)
    REFERENCES public.decks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_exchange_batches_deck
    ON public.exchange_batches(deck_id);


ALTER TABLE IF EXISTS public.exchange_batches
    ADD CONSTRAINT exchange_batches_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.exchange_items
    ADD CONSTRAINT exchange_items_batch_id_fkey FOREIGN KEY (batch_id)
    REFERENCES public.exchange_batches (batch_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_exchange_items_batch
    ON public.exchange_items(batch_id);


ALTER TABLE IF EXISTS public.exchange_items
    ADD CONSTRAINT exchange_items_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exchange_print_stats
    ADD CONSTRAINT exchange_print_stats_batch_id_fkey FOREIGN KEY (batch_id)
    REFERENCES public.exchange_batches (batch_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS exchange_print_stats_pkey
    ON public.exchange_print_stats(batch_id);


ALTER TABLE IF EXISTS public.market_listing_items
    ADD CONSTRAINT market_listing_items_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_market_listing_items_card
    ON public.market_listing_items(card_id);


ALTER TABLE IF EXISTS public.market_listing_items
    ADD CONSTRAINT market_listing_items_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES public.market_listings (listing_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_market_listing_items_listing
    ON public.market_listing_items(listing_id);


ALTER TABLE IF EXISTS public.market_listings
    ADD CONSTRAINT market_listings_deck_id_fkey FOREIGN KEY (deck_id)
    REFERENCES public.decks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.market_listings
    ADD CONSTRAINT market_listings_seller_id_fkey FOREIGN KEY (seller_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.market_rate_tiers
    ADD CONSTRAINT market_rate_tiers_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES public.market_listings (listing_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_market_rate_tiers_listing
    ON public.market_rate_tiers(listing_id);


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notifications_user
    ON public.notifications(user_id);


ALTER TABLE IF EXISTS public.preset_aliases
    ADD CONSTRAINT preset_aliases_preset_id_fkey FOREIGN KEY (preset_id)
    REFERENCES public.presets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.settings
    ADD CONSTRAINT settings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS settings_pkey
    ON public.settings(user_id);


ALTER TABLE IF EXISTS public.uid_verification_confirmation_reminders
    ADD CONSTRAINT uid_verification_confirmation_reminders_conf_id_fkey FOREIGN KEY (conf_id)
    REFERENCES public.uid_verification_confirmations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.uid_verification_confirmations
    ADD CONSTRAINT uid_verification_confirmations_counterparty_user_id_fkey FOREIGN KEY (counterparty_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.uid_verification_confirmations
    ADD CONSTRAINT uid_verification_confirmations_request_id_fkey FOREIGN KEY (request_id)
    REFERENCES public.uid_verification_requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.uid_verification_events
    ADD CONSTRAINT uid_verification_events_request_id_fkey FOREIGN KEY (request_id)
    REFERENCES public.uid_verification_requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.uid_verification_requests
    ADD CONSTRAINT uid_verification_requests_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_bans
    ADD CONSTRAINT user_bans_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_preset_subscriptions
    ADD CONSTRAINT user_preset_subscriptions_preset_id_fkey FOREIGN KEY (preset_id)
    REFERENCES public.presets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_card
    ON public.user_subscriptions(card_id);


ALTER TABLE IF EXISTS public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user
    ON public.user_subscriptions(user_id);


ALTER TABLE IF EXISTS public.user_uids
    ADD CONSTRAINT user_uids_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS user_uids_user_id_key
    ON public.user_uids(user_id);


ALTER TABLE IF EXISTS public.user_warnings
    ADD CONSTRAINT user_warnings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;

-- OR

create table if not exists custom_emojis
(
    name     text not null
        constraint custom_emojis_pkey
            primary key,
    emoji_id text not null
        constraint custom_emojis_emoji_id_key
            unique
);

create table if not exists decks
(
    id        serial
        constraint decks_pkey
            primary key,
    name      varchar(255) not null,
    deck_type deck_type default 'resource'::deck_type
);

create table if not exists cards
(
    card_id         serial
        constraint cards_pkey
            primary key,
    deck_id         integer                                      not null
        constraint cards_deck_id_fkey
            references decks
            on update cascade on delete restrict
            deferrable initially deferred,
    num             integer                                      not null,
    hero_name       varchar(255)                                 not null,
    image_id        text,
    rarity          varchar(50)                                  not null,
    story           varchar(255)                                 not null,
    quote           text,
    card_name       varchar(255) default ''::character varying   not null,
    obtain_type     obtain_type  default 'diamonds'::obtain_type not null,
    obtain_amount   integer      default 0                       not null,
    media_type      text         default 'photo'::text           not null,
    media_file_id   text,
    media_unique_id text,
    thumb_file_id   text
);

create table if not exists auctions
(
    auction_id            serial
        constraint auctions_pkey
            primary key,
    card_name             varchar(255)                                      not null,
    hero_name             varchar(255),
    image_id              text,
    start_price           integer     default 0                             not null,
    start_time            timestamp with time zone                          not null,
    end_time              timestamp with time zone                          not null,
    status                varchar(20) default 'scheduled'::character varying
        constraint chk_auctions_status
            check ((status)::text = ANY
                   ((ARRAY ['draft'::character varying, 'moderation'::character varying,
                       'pending'::character varying, 'approved'::character varying,
                       'scheduled'::character varying, 'publishing'::character varying,
                       'publication_failed'::character varying, 'active'::character varying,
                       'finalizing'::character varying, 'finalization_failed'::character varying,
                       'finished'::character varying, 'rejected'::character varying,
                       'cancelled'::character varying, 'closed'::character varying])::text[])),
    created_at            timestamp with time zone default CURRENT_TIMESTAMP,
    currency              varchar(20) default 'чашки'::character varying
        constraint chk_auctions_currency
            check ((currency)::text = ANY
                   ((ARRAY ['алмазы'::character varying, 'чашки'::character varying, 'сокровища'::character varying])::text[])),
    comment               text,
    message_id            bigint,
    notified_start        boolean     default false,
    notified_1min         boolean     default false,
    notified_end          boolean     default false,
    proof_photo_id        text,
    discussion_message_id bigint,
    notified_card_subs    boolean     default false,
    auction_kind          varchar(20) default 'standard'::character varying not null
        constraint auctions_auction_kind_chk
            check ((auction_kind)::text = ANY
                   ((ARRAY ['standard'::character varying, 'reverse'::character varying, 'fast'::character varying, 'free'::character varying, 'black'::character varying, 'exchange'::character varying])::text[])),
    craft_uid_possible    boolean,
    card_id               integer
        constraint auctions_card_id_fkey
            references cards
            on delete set null,
    finalization_started_at timestamp with time zone,
    finalization_finished_at timestamp with time zone,
    finalization_attempts integer default 0 not null,
    finalization_error text,
    publication_started_at timestamp with time zone,
    publication_finished_at timestamp with time zone,
    publication_next_attempt_at timestamp with time zone,
    publication_attempts integer default 0 not null,
    publication_error text,
    constraint chk_auctions_time_order
        check (
            CASE
                WHEN ((status)::text = ANY
                      ((ARRAY ['scheduled'::character varying, 'publishing'::character varying,
                          'publication_failed'::character varying, 'active'::character varying,
                          'finalizing'::character varying, 'finalization_failed'::character varying,
                          'finished'::character varying])::text[]))
                    THEN (end_time > start_time)
                ELSE true
                END)
);

create unique index if not exists ux_auctions_discussion_msg
    on auctions (discussion_message_id)
    where (discussion_message_id IS NOT NULL);

create unique index if not exists ux_auctions_message_id
    on auctions (message_id)
    where (message_id IS NOT NULL);

create index if not exists idx_auctions_status_endtime
    on auctions (status, end_time);

create index if not exists idx_auctions_status_starttime
    on auctions (status, start_time);

create index if not exists idx_auctions_start_time
    on auctions (start_time);

create index if not exists idx_auctions_card_name_trgm
    on auctions using gin (card_name gin_trgm_ops);

create index if not exists idx_auctions_hero_name_trgm
    on auctions using gin (hero_name gin_trgm_ops);

create index if not exists idx_auctions_sched_by_start
    on auctions (start_time)
    where ((status)::text = 'scheduled'::text);

create index if not exists idx_auctions_start_time_date
    on auctions (((start_time at time zone 'Europe/Moscow')::date));

create index if not exists idx_auctions_status_names
    on auctions (status, lower(card_name::text), lower(hero_name::text));

create index if not exists idx_auctions_active_end
    on auctions (end_time)
    where ((status)::text = ANY ((ARRAY ['scheduled'::character varying, 'active'::character varying])::text[]));

create index if not exists idx_auctions_kind
    on auctions (auction_kind);

create index if not exists idx_auctions_card_id
    on auctions (card_id);

create trigger trg_no_currency_flip
    before update
        of currency
    on auctions
    for each row
execute procedure prevent_currency_change_if_bids();

create trigger trg_prevent_time_change
    before update
    on auctions
    for each row
execute procedure prevent_time_change_if_bids();

create trigger trg_auctions_fix_end_time
    before insert or update
        of start_time
    on auctions
    for each row
execute procedure auctions_fix_end_time();

create index if not exists idx_cards_hero_trgm
    on cards using gin (hero_name gin_trgm_ops);

create index if not exists idx_cards_name_trgm
    on cards using gin (card_name gin_trgm_ops);

create index if not exists idx_cards_hero
    on cards (hero_name);

create index if not exists idx_cards_name
    on cards (card_name);

create index if not exists idx_cards_deck_num
    on cards (deck_id, num);

create table if not exists trusted_usernames
(
    username varchar(32) not null
        constraint trusted_usernames_pkey
            primary key
);

create table if not exists user_appeals
(
    id                 bigserial
        constraint user_appeals_pkey
            primary key,
    user_id            bigint                                           not null,
    username           text,
    topic              text                                             not null,
    description        text                                             not null,
    participants       text,
    media_message_ids  integer[]                default '{}'::integer[],
    origin_chat_id     bigint                                           not null,
    status             text                     default 'pending'::text not null,
    moderator_id       bigint,
    moderator_username text,
    moderator_comment  text,
    created_at         timestamp with time zone default now()           not null,
    updated_at         timestamp with time zone default now()           not null
);

create trigger trg_user_appeals_touch
    before update
    on user_appeals
    for each row
execute procedure set_updated_at();

create table if not exists users
(
    user_id                     bigint              not null
        constraint users_pkey
            primary key,
    username                    varchar(32),
    full_name                   varchar(255),
    is_subscribed               boolean   default true,
    is_luxury                   boolean   default false,
    warnings_count              integer   default 0,
    created_at                  timestamp default CURRENT_TIMESTAMP,
    is_trusted                  boolean   default false,
    pm_opened                   boolean   default false,
    first_pm_at                 timestamp,
    last_pm_at                  timestamp,
    uid_verif_confirmed_count   integer   default 0 not null,
    uid_verif_rejected_count    integer   default 0 not null,
    uid_verif_last_confirmed_at timestamp with time zone,
    uid_verif_last_rejected_at  timestamp with time zone
);

create table if not exists admins
(
    user_id  bigint not null
        constraint admins_pkey
            primary key
        constraint admins_user_id_fkey
            references users
            on delete cascade,
    username text,
    added_by bigint,
    added_at timestamp default CURRENT_TIMESTAMP
);

create table if not exists auction_owners
(
    id           serial
        constraint auction_owners_pkey
            primary key,
    auction_id   integer                      not null
        constraint auction_owners_auction_id_fkey
            references auctions
            on delete cascade,
    user_id      bigint                       not null
        constraint auction_owners_user_id_fkey
            references users
            on delete cascade,
    folder       text default 'default'::text not null
        constraint auction_owners_folder_chk
            check (folder = ANY (ARRAY ['default'::text, 'archived'::text, 'payable'::text])),
    owner_folder text default 'default'::text not null,
    constraint ux_auction_owners
        unique (auction_id, user_id)
);

create index if not exists idx_auction_owners_auction_id
    on auction_owners (auction_id);

create index if not exists idx_auction_owners_user_id
    on auction_owners (user_id);

create index if not exists idx_auction_owners_user_folder
    on auction_owners (user_id, folder);

create table if not exists audit_logs
(
    id          serial
        constraint audit_logs_pkey
            primary key,
    user_id     bigint
        constraint fk_audit_user
            references users
            on delete set null,
    action_type varchar(50) not null,
    auction_id  bigint
        constraint fk_audit_auction
            references auctions
            on delete cascade,
    details     text,
    created_at  timestamp default CURRENT_TIMESTAMP
);

create index if not exists idx_audit_user_time
    on audit_logs (user_id asc, created_at desc);

create index if not exists idx_audit_auction_time
    on audit_logs (auction_id asc, created_at desc);

create table if not exists bids
(
    bid_id                serial
        constraint bids_pkey
            primary key,
    auction_id            integer not null
        constraint bids_auction_id_fkey
            references auctions
            on delete cascade,
    bidder_id             bigint  not null
        constraint bids_bidder_id_fkey
            references users
            on delete cascade,
    amount                integer not null
        constraint chk_bids_amount_positive
            check (amount > 0)
        constraint ck_bids_positive
            check (amount > 0),
    placed_at             timestamp with time zone default CURRENT_TIMESTAMP,
    discussion_message_id bigint,
    created_at            timestamp with time zone default CURRENT_TIMESTAMP,
    constraint chk_bids_step_and_min_by_currency
        check (is_valid_bid(auction_id, amount))
);

create index if not exists idx_bids_auction_sort
    on bids (auction_id asc, amount desc, placed_at asc);

create index if not exists idx_bids_discussion_msg
    on bids (discussion_message_id asc, placed_at desc);

create index if not exists idx_bids_auction
    on bids (auction_id);

create index if not exists idx_bids_bidder
    on bids (bidder_id);

create table if not exists delete_requests
(
    id         serial
        constraint delete_requests_pkey
            primary key,
    lot_id     integer not null
        constraint delete_requests_lot_id_fkey
            references auctions
            on delete cascade,
    user_id    bigint  not null
        constraint delete_requests_user_id_fkey
            references users
            on delete cascade,
    reason     text,
    created_at timestamp   default CURRENT_TIMESTAMP,
    status     varchar(20) default 'pending'::character varying
);

create table if not exists notifications
(
    notification_id   serial
        constraint notifications_pkey
            primary key,
    user_id           bigint  not null
        constraint notifications_user_id_fkey
            references users
            on delete cascade,
    auction_id        integer not null
        constraint notifications_auction_id_fkey
            references auctions
            on delete cascade,
    notification_type varchar(50),
    sent_at           timestamp default CURRENT_TIMESTAMP
);

create index if not exists idx_notifications_user
    on notifications (user_id);

create table if not exists settings
(
    user_id              bigint not null
        constraint settings_pkey
            primary key
        constraint settings_user_id_fkey
            references users
            on delete cascade,
    notify_auction_start boolean default true,
    notify_bid_reminder  boolean default true,
    notify_auction_end   boolean default true,
    notify_daily_today   boolean default false
);

create table if not exists user_bans
(
    id           serial
        constraint user_bans_pkey
            primary key,
    user_id      bigint not null
        constraint user_bans_user_id_fkey
            references users
            on delete cascade,
    banned_until timestamp,
    reason       varchar(255),
    issued_at    timestamp default CURRENT_TIMESTAMP
);

create table if not exists user_subscriptions
(
    id                serial
        constraint user_subscriptions_pkey
            primary key,
    user_id           bigint  not null
        constraint user_subscriptions_user_id_fkey
            references users
            on delete cascade,
    card_id           integer not null
        constraint user_subscriptions_card_id_fkey
            references cards
            on delete cascade,
    created_at        timestamp default CURRENT_TIMESTAMP,
    last_confirmed_at timestamp with time zone,
    constraint ux_user_subscriptions
        unique (user_id, card_id)
);

create index if not exists idx_user_subscriptions_user
    on user_subscriptions (user_id);

create index if not exists idx_user_subscriptions_card
    on user_subscriptions (card_id);

create index if not exists idx_user_subs_last_confirmed
    on user_subscriptions (user_id asc, last_confirmed_at desc);

create table if not exists user_warnings
(
    id        serial
        constraint user_warnings_pkey
            primary key,
    user_id   bigint not null
        constraint user_warnings_user_id_fkey
            references users
            on delete cascade,
    reason    varchar(255),
    issued_at timestamp default CURRENT_TIMESTAMP,
    details   text
);

create unique index if not exists ux_users_username_ci
    on users (lower(username::text))
    where ((username IS NOT NULL) AND ((username)::text <> ''::text));

create index if not exists idx_users_is_luxury
    on users (is_luxury);

create table if not exists card_day_notifications
(
    id      bigserial
        constraint card_day_notifications_pkey
            primary key,
    user_id bigint                  not null,
    card_id bigint                  not null,
    day     date                    not null,
    sent_at timestamp default now() not null,
    constraint card_day_notifications_user_id_card_id_day_key
        unique (user_id, card_id, day)
);

create table if not exists unreachable_users
(
    user_id   bigint                  not null
        constraint unreachable_users_pkey
            primary key,
    reason    text                    not null,
    last_seen timestamp default now() not null
);

create table if not exists presets
(
    id    bigserial
        constraint presets_pkey
            primary key,
    key   text not null
        constraint presets_key_key
            unique,
    title text not null
);

create table if not exists preset_aliases
(
    preset_id bigint not null
        constraint preset_aliases_preset_id_fkey
            references presets
            on delete cascade,
    alias     text   not null,
    constraint preset_aliases_pkey
        primary key (preset_id, alias)
);

create table if not exists user_preset_subscriptions
(
    id         bigserial
        constraint user_preset_subscriptions_pkey
            primary key,
    user_id    bigint                                 not null,
    preset_id  bigint                                 not null
        constraint user_preset_subscriptions_preset_id_fkey
            references presets
            on delete cascade,
    created_at timestamp with time zone default now() not null,
    constraint user_preset_subscriptions_user_id_preset_id_key
        unique (user_id, preset_id)
);

create table if not exists market_listings
(
    listing_id    serial
        constraint market_listings_pkey
            primary key,
    seller_id     bigint                                           not null
        constraint market_listings_seller_id_fkey
            references users
            on delete cascade,
    status        listing_status  default 'active'::listing_status not null,
    description   text,
    currency_type market_currency default 'cash'::market_currency  not null,
    cash_code     varchar(8),
    price_num     numeric(14, 2)  default 0                        not null
        constraint ck_ml_price_nonneg
            check (price_num >= (0)::numeric),
    created_at    timestamp       default now()                    not null,
    updated_at    timestamp       default now()                    not null,
    offer_kind    offer_kind      default 'cards'::offer_kind      not null,
    cover_file_id text,
    channel_id    bigint,
    message_id    bigint,
    deck_id       integer
        constraint market_listings_deck_id_fkey
            references decks
            on delete set null,
    proof_file_id text,
    proof_by_card jsonb           default '{}'::jsonb
);

create index if not exists idx_market_listings_seller_status
    on market_listings (seller_id, status);

create index if not exists idx_market_listings_currency
    on market_listings (currency_type, cash_code);

create index if not exists idx_market_listings_status_updated
    on market_listings (status asc, updated_at desc);

create index if not exists idx_market_listings_kind
    on market_listings (offer_kind);

create trigger trg_market_listings_touch
    before update
    on market_listings
    for each row
execute procedure set_updated_at();

create table if not exists market_listing_items
(
    id            serial
        constraint market_listing_items_pkey
            primary key,
    listing_id    integer           not null
        constraint market_listing_items_listing_id_fkey
            references market_listings
            on delete cascade,
    card_id       integer           not null
        constraint market_listing_items_card_id_fkey
            references cards
            on delete cascade,
    quantity      integer default 1 not null
        constraint ck_mli_qty_pos
            check (quantity > 0),
    proof_file_id text,
    constraint ux_mli
        unique (listing_id, card_id)
);

create index if not exists idx_market_listing_items_listing
    on market_listing_items (listing_id);

create index if not exists idx_market_listing_items_card
    on market_listing_items (card_id);

create unique index if not exists uq_market_listing_items
    on market_listing_items (listing_id, card_id);

create table if not exists market_rate_tiers
(
    id         serial
        constraint market_rate_tiers_pkey
            primary key,
    listing_id integer           not null
        constraint market_rate_tiers_listing_id_fkey
            references market_listings
            on delete cascade,
    label      text,
    qty        integer
        constraint ck_mrt_qty_nonneg
            check ((qty IS NULL) OR (qty >= 0)),
    pay_type   market_currency   not null,
    cash_code  varchar(8),
    price      numeric(14, 2)    not null
        constraint ck_mrt_price_nonneg
            check (price >= (0)::numeric),
    sort_order integer default 0 not null
);

create index if not exists idx_mrt_listing
    on market_rate_tiers (listing_id, sort_order);

create index if not exists idx_market_rate_tiers_listing
    on market_rate_tiers (listing_id);

create table if not exists exchange_batches
(
    batch_id               bigserial
        constraint exchange_batches_pkey
            primary key,
    user_id                bigint                                            not null
        constraint exchange_batches_user_id_fkey
            references users
            on delete cascade,
    deck_id                integer                                           not null
        constraint exchange_batches_deck_id_fkey
            references decks,
    mode                   text                                              not null
        constraint exchange_batches_mode_check
            check (mode = ANY (ARRAY ['card'::text, 'deck'::text, 'deck_split'::text])),
    currency               text                                              not null,
    price                  integer                                           not null,
    comment                text,
    proof_photo_id         text                     default 'NO_PROOF'::text not null,
    created_at             timestamp with time zone default now()            not null,
    status                 text                     default 'pending'::text  not null
        constraint chk_exchange_batches_status
            check (status = ANY (ARRAY [
                'pending'::text, 'approved'::text, 'rejected'::text,
                'publishing'::text, 'publication_failed'::text,
                'published'::text, 'deleted'::text
            ])),
    moderator_id           bigint,
    moderator_username     text,
    moderator_comment      text,
    moderated_at           timestamp with time zone,
    moderated_by           bigint,
    moderated_username     text,
    moderated_comment      text,
    manual_winner_id       bigint,
    manual_winner_username text,
    manual_price           integer,
    manual_link            text,
    manual_set_by          bigint,
    manual_set_at          timestamp with time zone,
    manual_sent_at         timestamp with time zone,
    posted_chat_id         bigint,
    posted_message_id      bigint,
    posted_at              timestamp with time zone,
    publication_started_at timestamp with time zone,
    publication_finished_at timestamp with time zone,
    publication_error      text,
    deleted_at             timestamp with time zone
);

create index if not exists idx_exchange_batches_status
    on exchange_batches (status);

create index if not exists idx_exchange_batches_deck
    on exchange_batches (deck_id);

create index if not exists idx_exchange_batches_status_created
    on exchange_batches (status asc, created_at desc);

create table if not exists exchange_items
(
    item_id    bigserial
        constraint exchange_items_pkey
            primary key,
    batch_id   bigint                                 not null
        constraint exchange_items_batch_id_fkey
            references exchange_batches
            on delete cascade,
    card_id    integer
        constraint exchange_items_card_id_fkey
            references cards,
    card_name  text,
    hero_name  text,
    created_at timestamp with time zone default now() not null
);

create index if not exists idx_exchange_items_batch
    on exchange_items (batch_id);

create index if not exists ix_exchange_items_batch_card
    on exchange_items (batch_id, card_id)
    where (card_id IS NOT NULL);

create index if not exists ix_auctions_publication_queue
    on auctions (status, publication_next_attempt_at, start_time, auction_id)
    where message_id is null
      and status in ('scheduled', 'publishing', 'publication_failed');

create index if not exists ix_auctions_schedule_conflicts
    on auctions (start_time, end_time, auction_id)
    where status in ('scheduled', 'publishing', 'active');

create index if not exists ix_bids_auction_lowest_winner_order
    on bids (auction_id, amount asc, placed_at asc, bid_id asc);

create unique index if not exists ux_exchange_batches_posted_message
    on exchange_batches (posted_chat_id, posted_message_id)
    where posted_chat_id is not null and posted_message_id is not null;

create index if not exists ix_exchange_batches_moderation_queue
    on exchange_batches (status, created_at, batch_id)
    where deleted_at is null;

create table if not exists guides_thanks
(
    user_id      bigint              not null
        constraint guides_thanks_pkey
            primary key,
    thanks_count integer   default 0 not null,
    last_at      timestamp default CURRENT_TIMESTAMP
);

create table if not exists admin_thanks_totals
(
    author       text                not null
        constraint admin_thanks_totals_pkey
            primary key,
    thanks_total bigint    default 0 not null,
    users_total  bigint    default 0 not null,
    updated_at   timestamp default CURRENT_TIMESTAMP
);

create table if not exists admin_thanks_users
(
    author       text                not null,
    user_id      bigint              not null,
    created_at   timestamp default CURRENT_TIMESTAMP,
    thanks_count bigint    default 0 not null,
    constraint admin_thanks_users_pkey
        primary key (author, user_id)
);

create table if not exists auction_win_mailings
(
    id               bigserial
        constraint auction_win_mailings_pkey
            primary key,
    auction_id       integer not null,
    target           text    not null,
    sent_by_user_id  bigint,
    sent_by_username text,
    sent_at          timestamp default CURRENT_TIMESTAMP
);

create index if not exists idx_auction_win_mailings_auction_id
    on auction_win_mailings (auction_id);

create table if not exists auction_manual_results
(
    auction_id      integer not null
        constraint auction_manual_results_pkey
            primary key,
    winner_user_id  bigint,
    winner_username text,
    owner_user_id   bigint,
    owner_username  text,
    amount          integer,
    updated_at      timestamp default CURRENT_TIMESTAMP,
    updated_by      bigint
);

create table if not exists auctions_image_id_backup
(
    auction_id   integer not null
        constraint auctions_image_id_backup_pkey
            primary key,
    old_image_id text,
    backed_up_at timestamp default now()
);

create table if not exists auction_posts_backfill
(
    post_id          bigint            not null
        constraint auction_posts_backfill_pkey
            primary key,
    post_link        text              not null,
    post_date_msk    timestamp,
    end_time_msk     timestamp,
    deadline_msk     timestamp,
    root_id          bigint,
    discussion_id    bigint,
    msgs_scanned     integer default 0 not null,
    numeric_msgs     integer default 0 not null,
    thread_bids      integer default 0 not null,
    thread_valid     integer default 0 not null,
    max_thread_valid bigint,
    winner_id        bigint,
    any_valid        integer default 0 not null,
    max_any_valid    bigint,
    note             text
);

create index if not exists idx_apb_post_date
    on auction_posts_backfill (post_date_msk);

create index if not exists idx_apb_post_day
    on auction_posts_backfill ((post_date_msk::date));

create table if not exists auction_posts_stats
(
    post_id           bigint                not null
        constraint auction_posts_stats_pkey
            primary key
        constraint auction_posts_stats_post_id_fkey
            references auction_posts_backfill
            on delete cascade,
    checked           boolean default false not null,
    checked_by        bigint,
    checked_at        timestamp,
    manual_winner_id  bigint,
    manual_max_bid    bigint,
    manual_valid_bids integer,
    manual_total_bids integer,
    manual_note       text,
    excluded          boolean default false not null,
    excluded_by       bigint,
    excluded_at       timestamp,
    excluded_reason   text,
    ordinal_no        integer,
    manual_date       date,
    manual_time       time,
    deck_no           integer,
    card_title        text,
    bidders_count     integer,
    min_bid           bigint,
    max_bid           bigint,
    owner_id          bigint,
    manual_link       text
);

create index if not exists idx_aps_checked
    on auction_posts_stats (checked);

create index if not exists idx_aps_excluded
    on auction_posts_stats (excluded);

create index if not exists idx_aps_deck_no
    on auction_posts_stats (deck_no);

create index if not exists idx_aps_card_title
    on auction_posts_stats (card_title);

create table if not exists exchange_print_stats
(
    batch_id           integer                                not null
        constraint exchange_print_stats_pkey
            primary key
        constraint exchange_print_stats_batch_id_fkey
            references exchange_batches
            on delete cascade,
    manual_winner_id   bigint,
    manual_winner_name text,
    manual_price       integer,
    manual_link        text,
    updated_by         bigint,
    updated_at         timestamp with time zone default now() not null
);

create index if not exists idx_exchange_print_stats_updated_at
    on exchange_print_stats (updated_at desc);

create table if not exists autobids
(
    autobid_id      serial
        constraint autobids_pkey
            primary key,
    auction_id      integer                                not null
        constraint autobids_auction_id_fkey
            references auctions
            on delete cascade,
    target_user_id  bigint                                 not null,
    target_username text,
    max_amount      integer                                not null
        constraint autobids_max_amount_check
            check (max_amount > 0),
    step            integer                  default 10    not null
        constraint autobids_step_check
            check (step > 0),
    is_active       boolean                  default true  not null,
    created_by      bigint                                 not null,
    created_at      timestamp with time zone default now() not null,
    updated_at      timestamp with time zone default now() not null,
    constraint autobids_auction_user_uniq
        unique (auction_id, target_user_id)
);

create table if not exists autobid_actions
(
    action_id             serial
        constraint autobid_actions_pkey
            primary key,
    autobid_id            integer                                not null
        constraint autobid_actions_autobid_id_fkey
            references autobids
            on delete cascade,
    auction_id            integer                                not null
        constraint autobid_actions_auction_id_fkey
            references auctions
            on delete cascade,
    target_user_id        bigint                                 not null,
    amount                integer                                not null
        constraint autobid_actions_amount_check
            check (amount > 0),
    discussion_message_id bigint                                 not null
        constraint autobid_actions_discussion_message_id_key
            unique,
    sent_at               timestamp with time zone default now() not null
);

create index if not exists autobid_actions_auction_id_idx
    on autobid_actions (auction_id);

create table if not exists user_uids
(
    uid         text                                              not null
        constraint user_uids_pkey
            primary key,
    user_id     bigint                                            not null
        constraint user_uids_user_id_key
            unique
        constraint user_uids_user_id_fkey
            references users
            on delete cascade,
    status      text                     default 'verified'::text not null
        constraint user_uids_status_check
            check (status = ANY (ARRAY ['verified'::text, 'revoked'::text])),
    verified_at timestamp with time zone default now()            not null,
    verified_by bigint,
    updated_at  timestamp with time zone default now()            not null
);

create table if not exists uid_verification_requests
(
    id                     bigserial
        constraint uid_verification_requests_pkey
            primary key,
    user_id                bigint                                           not null
        constraint uid_verification_requests_user_id_fkey
            references users
            on delete cascade,
    uid                    text                                             not null,
    challenge_code         text                                             not null,
    profile_file_id        text                                             not null,
    deal_file_ids          text[]                   default '{}'::text[]    not null,
    status                 text                     default 'pending'::text not null
        constraint uid_verification_requests_status_check
            check (status = ANY
                   (ARRAY ['pending'::text, 'approved'::text, 'rejected'::text, 'conflict'::text, 'expired'::text, 'revision'::text])),
    created_at             timestamp with time zone default now()           not null,
    decided_at             timestamp with time zone,
    decided_by             bigint,
    admin_comment          text,
    uid_proof_file_id      text,
    profile_proof_file_id  text,
    verification_code      text                                             not null,
    counterparty_usernames text[]                   default '{}'::text[]    not null,
    reg_date_proof_file_id text,
    extra_proof_file_ids   text[]                   default '{}'::text[]    not null,
    revision_flags         text[]                   default '{}'::text[]    not null,
    revision_reason        text,
    revision_requested_at  timestamp with time zone,
    revision_by            bigint,
    revision_by_username   text,
    revision_at            timestamp with time zone,
    revision_returned_at   timestamp with time zone,
    revision_completed_at  timestamp with time zone
);

create index if not exists idx_uid_verif_req_status_created
    on uid_verification_requests (status asc, created_at desc);

create index if not exists idx_uid_verif_req_uid
    on uid_verification_requests (uid);

create trigger trg_uid_verif_sync_cols
    before insert or update
    on uid_verification_requests
    for each row
execute procedure uid_verif_sync_cols();

create table if not exists uid_bans
(
    uid          text                                   not null
        constraint uid_bans_pkey
            primary key,
    reason       text,
    banned_by    bigint,
    banned_at    timestamp with time zone default now() not null,
    banned_until timestamp with time zone
);

create index if not exists idx_uid_bans_until
    on uid_bans (banned_until);

create table if not exists uid_verification_confirmations
(
    id                    bigserial
        constraint uid_verification_confirmations_pkey
            primary key,
    request_id            bigint                                           not null
        constraint uid_verification_confirmations_request_id_fkey
            references uid_verification_requests
            on delete cascade,
    counterparty_user_id  bigint
        constraint uid_verification_confirmations_counterparty_user_id_fkey
            references users
            on delete set null,
    counterparty_username text                                             not null,
    status                text                     default 'pending'::text not null
        constraint uid_verification_confirmations_status_check
            check (status = ANY (ARRAY ['pending'::text, 'confirmed'::text, 'rejected'::text, 'unreachable'::text])),
    created_at            timestamp with time zone default now()           not null,
    decided_at            timestamp with time zone,
    message_chat_id       bigint,
    message_id            bigint,
    constraint ux_uid_verif_conf_req_username
        unique (request_id, counterparty_username)
);

create table if not exists admin_thanks_clicks
(
    chat_id    bigint              not null,
    message_id integer             not null,
    user_id    bigint              not null,
    author     text                not null,
    item_id    bigint    default 0 not null,
    created_at timestamp default CURRENT_TIMESTAMP,
    constraint admin_thanks_clicks_pkey
        primary key (chat_id, message_id, user_id)
);

create table if not exists uid_verification_events
(
    id             bigserial
        constraint uid_verification_events_pkey
            primary key,
    request_id     bigint                                       not null
        constraint uid_verification_events_request_id_fkey
            references uid_verification_requests
            on delete cascade,
    actor_id       bigint,
    actor_username text,
    event_type     text                                         not null,
    details        jsonb                    default '{}'::jsonb not null,
    created_at     timestamp with time zone default now()       not null
);

create index if not exists idx_uidv_events_req_time
    on uid_verification_events (request_id asc, created_at desc);

create table if not exists uid_verification_confirmation_reminders
(
    conf_id bigint                                 not null
        constraint uid_verification_confirmation_reminders_conf_id_fkey
            references uid_verification_confirmations
            on delete cascade,
    stage_h integer                                not null,
    sent_at timestamp with time zone default now() not null,
    constraint uid_verification_confirmation_reminders_pkey
        primary key (conf_id, stage_h)
);

