-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.admin_thanks_clicks
(
    chat_id bigint NOT NULL,
    message_id integer NOT NULL,
    user_id bigint NOT NULL,
    author text COLLATE pg_catalog."default" NOT NULL,
    item_id bigint NOT NULL DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_thanks_clicks_pkey PRIMARY KEY (chat_id, message_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.admin_thanks_totals
(
    author text COLLATE pg_catalog."default" NOT NULL,
    thanks_total bigint NOT NULL DEFAULT 0,
    users_total bigint NOT NULL DEFAULT 0,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admin_thanks_totals_pkey PRIMARY KEY (author)
);

CREATE TABLE IF NOT EXISTS public.admin_thanks_users
(
    author text COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    thanks_count bigint NOT NULL DEFAULT 0,
    CONSTRAINT admin_thanks_users_pkey PRIMARY KEY (author, user_id)
);

CREATE TABLE IF NOT EXISTS public.admins
(
    user_id bigint NOT NULL,
    username text COLLATE pg_catalog."default",
    added_by bigint,
    added_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT admins_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.auction_manual_results
(
    auction_id integer NOT NULL,
    winner_user_id bigint,
    winner_username text COLLATE pg_catalog."default",
    owner_user_id bigint,
    owner_username text COLLATE pg_catalog."default",
    amount integer,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_by bigint,
    moderator_comment text COLLATE pg_catalog."default",
    CONSTRAINT auction_manual_results_pkey PRIMARY KEY (auction_id)
);

CREATE TABLE IF NOT EXISTS public.auction_owners
(
    id serial NOT NULL,
    auction_id integer NOT NULL,
    user_id bigint NOT NULL,
    folder text COLLATE pg_catalog."default" NOT NULL DEFAULT 'default'::text,
    owner_folder text COLLATE pg_catalog."default" NOT NULL DEFAULT 'default'::text,
    CONSTRAINT auction_owners_pkey PRIMARY KEY (id),
    CONSTRAINT ux_auction_owners UNIQUE (auction_id, user_id)
);

CREATE TABLE IF NOT EXISTS public.auction_posts_backfill
(
    post_id bigint NOT NULL,
    post_link text COLLATE pg_catalog."default" NOT NULL,
    post_date_msk timestamp without time zone,
    end_time_msk timestamp without time zone,
    deadline_msk timestamp without time zone,
    root_id bigint,
    discussion_id bigint,
    msgs_scanned integer NOT NULL DEFAULT 0,
    numeric_msgs integer NOT NULL DEFAULT 0,
    thread_bids integer NOT NULL DEFAULT 0,
    thread_valid integer NOT NULL DEFAULT 0,
    max_thread_valid bigint,
    winner_id bigint,
    any_valid integer NOT NULL DEFAULT 0,
    max_any_valid bigint,
    note text COLLATE pg_catalog."default",
    CONSTRAINT auction_posts_backfill_pkey PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS public.auction_posts_stats
(
    post_id bigint NOT NULL,
    checked boolean NOT NULL DEFAULT false,
    checked_by bigint,
    checked_at timestamp without time zone,
    manual_winner_id bigint,
    manual_max_bid bigint,
    manual_valid_bids integer,
    manual_total_bids integer,
    manual_note text COLLATE pg_catalog."default",
    excluded boolean NOT NULL DEFAULT false,
    excluded_by bigint,
    excluded_at timestamp without time zone,
    excluded_reason text COLLATE pg_catalog."default",
    ordinal_no integer,
    manual_date date,
    manual_time time without time zone,
    deck_no integer,
    card_title text COLLATE pg_catalog."default",
    bidders_count integer,
    min_bid bigint,
    max_bid bigint,
    owner_id bigint,
    manual_link text COLLATE pg_catalog."default",
    CONSTRAINT auction_posts_stats_pkey PRIMARY KEY (post_id)
);

CREATE TABLE IF NOT EXISTS public.auction_win_mailings
(
    id bigserial NOT NULL,
    auction_id integer NOT NULL,
    target text COLLATE pg_catalog."default" NOT NULL,
    sent_by_user_id bigint,
    sent_by_username text COLLATE pg_catalog."default",
    sent_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT auction_win_mailings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.auctions
(
    auction_id serial NOT NULL,
    card_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    hero_name character varying(255) COLLATE pg_catalog."default",
    image_id text COLLATE pg_catalog."default",
    start_price integer NOT NULL DEFAULT 0,
    start_time timestamp with time zone NOT NULL,
    end_time timestamp with time zone NOT NULL,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'scheduled'::character varying,
    created_at timestamp with time zone DEFAULT now(),
    currency character varying(20) COLLATE pg_catalog."default" DEFAULT 'чашки'::character varying,
    accepted_currencies   text[] DEFAULT ARRAY['чашки'::text] NOT NULL,
    comment text COLLATE pg_catalog."default",
    message_id bigint,
    notified_start boolean DEFAULT false,
    notified_1min boolean DEFAULT false,
    notified_end boolean DEFAULT false,
    proof_photo_id text COLLATE pg_catalog."default",
    discussion_message_id bigint,
    notified_card_subs boolean DEFAULT false,
    auction_kind character varying(20) COLLATE pg_catalog."default" NOT NULL DEFAULT 'standard'::character varying,
    craft_uid_possible boolean,
    card_id integer,
    finalization_started_at timestamp with time zone,
    finalization_finished_at timestamp with time zone,
    finalization_attempts integer NOT NULL DEFAULT 0,
    finalization_error text COLLATE pg_catalog."default",
    publication_started_at timestamp with time zone,
    publication_finished_at timestamp with time zone,
    publication_next_attempt_at timestamp with time zone,
    publication_attempts integer NOT NULL DEFAULT 0,
    publication_error text COLLATE pg_catalog."default",
    CONSTRAINT auctions_pkey PRIMARY KEY (auction_id)
);

CREATE TABLE IF NOT EXISTS public.auctions_image_id_backup
(
    auction_id integer NOT NULL,
    old_image_id text COLLATE pg_catalog."default",
    backed_up_at timestamp without time zone DEFAULT now(),
    CONSTRAINT auctions_image_id_backup_pkey PRIMARY KEY (auction_id)
);

CREATE TABLE IF NOT EXISTS public.audit_logs
(
    id serial NOT NULL,
    user_id bigint,
    action_type character varying(50) COLLATE pg_catalog."default" NOT NULL,
    auction_id bigint,
    details text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT audit_logs_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.autobid_actions
(
    action_id serial NOT NULL,
    autobid_id integer NOT NULL,
    auction_id integer NOT NULL,
    target_user_id bigint NOT NULL,
    amount integer NOT NULL,
    discussion_message_id bigint NOT NULL,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT autobid_actions_pkey PRIMARY KEY (action_id),
    CONSTRAINT autobid_actions_discussion_message_id_key UNIQUE (discussion_message_id)
);

CREATE TABLE IF NOT EXISTS public.autobids
(
    autobid_id serial NOT NULL,
    auction_id integer NOT NULL,
    target_user_id bigint NOT NULL,
    target_username text COLLATE pg_catalog."default",
    max_amount integer NOT NULL,
    step integer NOT NULL DEFAULT 10,
    is_active boolean NOT NULL DEFAULT true,
    created_by bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT autobids_pkey PRIMARY KEY (autobid_id),
    CONSTRAINT autobids_auction_user_uniq UNIQUE (auction_id, target_user_id)
);

CREATE TABLE IF NOT EXISTS public.bid_duplicate_archive
(
    archive_id bigserial NOT NULL,
    original_bid_id bigint NOT NULL,
    bid_payload jsonb NOT NULL,
    archived_at timestamp with time zone NOT NULL DEFAULT now(),
    reason text COLLATE pg_catalog."default" NOT NULL DEFAULT 'duplicate discussion_message_id'::text,
    CONSTRAINT bid_duplicate_archive_pkey PRIMARY KEY (archive_id)
);

CREATE TABLE IF NOT EXISTS public.bids
(
    bid_id serial NOT NULL,
    auction_id integer NOT NULL,
    bidder_id bigint NOT NULL,
    amount integer NOT NULL,
    placed_at timestamp with time zone DEFAULT now(),
    discussion_message_id bigint,
    created_at timestamp with time zone DEFAULT now(),
    CONSTRAINT bids_pkey PRIMARY KEY (bid_id)
);

CREATE TABLE IF NOT EXISTS public.card_day_notifications
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    card_id bigint NOT NULL,
    day date NOT NULL,
    sent_at timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT card_day_notifications_pkey PRIMARY KEY (id),
    CONSTRAINT card_day_notifications_user_id_card_id_day_key UNIQUE (user_id, card_id, day)
);

CREATE TABLE IF NOT EXISTS public.cards
(
    card_id serial NOT NULL,
    deck_id integer NOT NULL,
    num integer NOT NULL,
    hero_name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    image_id text COLLATE pg_catalog."default",
    rarity character varying(50) COLLATE pg_catalog."default" NOT NULL,
    story character varying(255) COLLATE pg_catalog."default" NOT NULL,
    quote text COLLATE pg_catalog."default",
    card_name character varying(255) COLLATE pg_catalog."default" NOT NULL DEFAULT ''::character varying,
    obtain_type obtain_type NOT NULL DEFAULT 'diamonds'::obtain_type,
    obtain_amount integer NOT NULL DEFAULT 0,
    media_type text COLLATE pg_catalog."default" NOT NULL DEFAULT 'photo'::text,
    media_file_id text COLLATE pg_catalog."default",
    media_unique_id text COLLATE pg_catalog."default",
    thumb_file_id text COLLATE pg_catalog."default",
    CONSTRAINT cards_pkey PRIMARY KEY (card_id)
);

CREATE TABLE IF NOT EXISTS public.custom_emojis
(
    name text COLLATE pg_catalog."default" NOT NULL,
    emoji_id text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT custom_emojis_pkey PRIMARY KEY (name),
    CONSTRAINT custom_emojis_emoji_id_key UNIQUE (emoji_id)
);

CREATE TABLE IF NOT EXISTS public.decks
(
    id serial NOT NULL,
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    deck_type deck_type DEFAULT 'resource'::deck_type,
    CONSTRAINT decks_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.delete_requests
(
    id serial NOT NULL,
    lot_id integer NOT NULL,
    user_id bigint NOT NULL,
    reason text COLLATE pg_catalog."default",
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    status character varying(20) COLLATE pg_catalog."default" DEFAULT 'pending'::character varying,
    CONSTRAINT delete_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.exchange_batches
(
    batch_id bigserial NOT NULL,
    user_id bigint NOT NULL,
    deck_id integer NOT NULL,
    mode text COLLATE pg_catalog."default" NOT NULL,
    currency text COLLATE pg_catalog."default" NOT NULL,
    price integer NOT NULL,
    comment text COLLATE pg_catalog."default",
    proof_photo_id text COLLATE pg_catalog."default" NOT NULL DEFAULT 'NO_PROOF'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    moderator_id bigint,
    moderator_username text COLLATE pg_catalog."default",
    moderator_comment text COLLATE pg_catalog."default",
    moderated_at timestamp with time zone,
    moderated_by bigint,
    moderated_username text COLLATE pg_catalog."default",
    moderated_comment text COLLATE pg_catalog."default",
    manual_winner_id bigint,
    manual_winner_username text COLLATE pg_catalog."default",
    manual_price integer,
    manual_link text COLLATE pg_catalog."default",
    manual_set_by bigint,
    manual_set_at timestamp with time zone,
    manual_sent_at timestamp with time zone,
    posted_chat_id bigint,
    posted_message_id bigint,
    posted_at timestamp with time zone,
    deleted_at timestamp with time zone,
    publication_started_at timestamp with time zone,
    publication_finished_at timestamp with time zone,
    publication_error text COLLATE pg_catalog."default",
    CONSTRAINT exchange_batches_pkey PRIMARY KEY (batch_id)
);

CREATE TABLE IF NOT EXISTS public.exchange_items
(
    item_id bigserial NOT NULL,
    batch_id bigint NOT NULL,
    card_id integer,
    card_name text COLLATE pg_catalog."default",
    hero_name text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT exchange_items_pkey PRIMARY KEY (item_id)
);

CREATE TABLE IF NOT EXISTS public.exchange_print_stats
(
    batch_id integer NOT NULL,
    manual_winner_id bigint,
    manual_winner_name text COLLATE pg_catalog."default",
    manual_price integer,
    manual_link text COLLATE pg_catalog."default",
    updated_by bigint,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT exchange_print_stats_pkey PRIMARY KEY (batch_id)
);

CREATE TABLE IF NOT EXISTS public.guides_thanks
(
    user_id bigint NOT NULL,
    thanks_count integer NOT NULL DEFAULT 0,
    last_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT guides_thanks_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.market_listing_items
(
    id serial NOT NULL,
    listing_id integer NOT NULL,
    card_id integer NOT NULL,
    quantity integer NOT NULL DEFAULT 1,
    proof_file_id text COLLATE pg_catalog."default",
    CONSTRAINT market_listing_items_pkey PRIMARY KEY (id),
    CONSTRAINT ux_mli UNIQUE (listing_id, card_id)
);

CREATE TABLE IF NOT EXISTS public.market_listings
(
    listing_id serial NOT NULL,
    seller_id bigint NOT NULL,
    status listing_status NOT NULL DEFAULT 'active'::listing_status,
    description text COLLATE pg_catalog."default",
    currency_type market_currency NOT NULL DEFAULT 'cash'::market_currency,
    cash_code character varying(8) COLLATE pg_catalog."default",
    price_num numeric(14, 2) NOT NULL DEFAULT 0,
    created_at timestamp without time zone NOT NULL DEFAULT now(),
    updated_at timestamp without time zone NOT NULL DEFAULT now(),
    offer_kind offer_kind NOT NULL DEFAULT 'cards'::offer_kind,
    cover_file_id text COLLATE pg_catalog."default",
    channel_id bigint,
    message_id bigint,
    deck_id integer,
    proof_file_id text COLLATE pg_catalog."default",
    proof_by_card jsonb DEFAULT '{}'::jsonb,
    CONSTRAINT market_listings_pkey PRIMARY KEY (listing_id)
);

CREATE TABLE IF NOT EXISTS public.market_rate_tiers
(
    id serial NOT NULL,
    listing_id integer NOT NULL,
    label text COLLATE pg_catalog."default",
    qty integer,
    pay_type market_currency NOT NULL,
    cash_code character varying(8) COLLATE pg_catalog."default",
    price numeric(14, 2) NOT NULL,
    sort_order integer NOT NULL DEFAULT 0,
    CONSTRAINT market_rate_tiers_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.notifications
(
    notification_id serial NOT NULL,
    user_id bigint NOT NULL,
    auction_id integer NOT NULL,
    notification_type character varying(50) COLLATE pg_catalog."default",
    sent_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT notifications_pkey PRIMARY KEY (notification_id)
);

CREATE TABLE IF NOT EXISTS public.preset_aliases
(
    preset_id bigint NOT NULL,
    alias text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT preset_aliases_pkey PRIMARY KEY (preset_id, alias)
);

CREATE TABLE IF NOT EXISTS public.presets
(
    id bigserial NOT NULL,
    key text COLLATE pg_catalog."default" NOT NULL,
    title text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT presets_pkey PRIMARY KEY (id),
    CONSTRAINT presets_key_key UNIQUE (key),
    CONSTRAINT presets_key_uniq UNIQUE (key)
);

CREATE TABLE IF NOT EXISTS public.schema_migrations
(
    version text COLLATE pg_catalog."default" NOT NULL,
    checksum text COLLATE pg_catalog."default" NOT NULL,
    applied_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT schema_migrations_pkey PRIMARY KEY (version)
);

CREATE TABLE IF NOT EXISTS public.settings
(
    user_id bigint NOT NULL,
    notify_auction_start boolean DEFAULT true,
    notify_bid_reminder boolean DEFAULT true,
    notify_auction_end boolean DEFAULT true,
    notify_daily_today boolean DEFAULT false,
    CONSTRAINT settings_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.telegram_outbox
(
    outbox_id bigserial NOT NULL,
    dedupe_key text COLLATE pg_catalog."default" NOT NULL,
    method text COLLATE pg_catalog."default" NOT NULL DEFAULT 'send_message'::text,
    chat_id bigint NOT NULL,
    payload jsonb NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    available_at timestamp with time zone NOT NULL DEFAULT now(),
    attempts integer NOT NULL DEFAULT 0,
    max_attempts integer NOT NULL DEFAULT 5,
    locked_at timestamp with time zone,
    sent_at timestamp with time zone,
    telegram_message_id bigint,
    last_error text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    topic text COLLATE pg_catalog."default" NOT NULL DEFAULT 'legacy'::text,
    delivery_state text COLLATE pg_catalog."default" NOT NULL DEFAULT 'not_attempted'::text,
    reviewed_at timestamp with time zone,
    reviewed_by bigint,
    review_note text COLLATE pg_catalog."default",
    CONSTRAINT telegram_outbox_pkey PRIMARY KEY (outbox_id),
    CONSTRAINT telegram_outbox_dedupe_key_key UNIQUE (dedupe_key)
);

CREATE TABLE IF NOT EXISTS public.trusted_usernames
(
    username character varying(32) COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT trusted_usernames_pkey PRIMARY KEY (username)
);

CREATE TABLE IF NOT EXISTS public.uid_bans
(
    uid text COLLATE pg_catalog."default" NOT NULL,
    reason text COLLATE pg_catalog."default",
    banned_by bigint,
    banned_at timestamp with time zone NOT NULL DEFAULT now(),
    banned_until timestamp with time zone,
    uid_hash text COLLATE pg_catalog."default",
    uid_enc text COLLATE pg_catalog."default",
    uid_last4 text COLLATE pg_catalog."default",
    CONSTRAINT uid_bans_pkey PRIMARY KEY (uid)
);

CREATE TABLE IF NOT EXISTS public.uid_verification_confirmation_reminders
(
    conf_id bigint NOT NULL,
    stage_h integer NOT NULL,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uid_verification_confirmation_reminders_pkey PRIMARY KEY (conf_id, stage_h)
);

CREATE TABLE IF NOT EXISTS public.uid_verification_confirmations
(
    id bigserial NOT NULL,
    request_id bigint NOT NULL,
    counterparty_user_id bigint,
    counterparty_username text COLLATE pg_catalog."default" NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    decided_at timestamp with time zone,
    message_chat_id bigint,
    message_id bigint,
    CONSTRAINT uid_verification_confirmations_pkey PRIMARY KEY (id),
    CONSTRAINT ux_uid_verif_conf_req_username UNIQUE (request_id, counterparty_username)
);

CREATE TABLE IF NOT EXISTS public.uid_verification_events
(
    id bigserial NOT NULL,
    request_id bigint NOT NULL,
    actor_id bigint,
    actor_username text COLLATE pg_catalog."default",
    event_type text COLLATE pg_catalog."default" NOT NULL,
    details jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uid_verification_events_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.uid_verification_request_reminders
(
    request_id bigint NOT NULL,
    stage_h smallint NOT NULL,
    sent_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT uid_verification_request_reminders_pkey PRIMARY KEY (request_id, stage_h)
);

CREATE TABLE IF NOT EXISTS public.uid_verification_requests
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    uid text COLLATE pg_catalog."default" NOT NULL,
    challenge_code text COLLATE pg_catalog."default" NOT NULL,
    profile_file_id text COLLATE pg_catalog."default" NOT NULL,
    deal_file_ids text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    decided_at timestamp with time zone,
    decided_by bigint,
    admin_comment text COLLATE pg_catalog."default",
    uid_proof_file_id text COLLATE pg_catalog."default",
    profile_proof_file_id text COLLATE pg_catalog."default",
    verification_code text COLLATE pg_catalog."default" NOT NULL,
    counterparty_usernames text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    reg_date_proof_file_id text COLLATE pg_catalog."default",
    extra_proof_file_ids text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    revision_flags text[] COLLATE pg_catalog."default" NOT NULL DEFAULT '{}'::text[],
    revision_reason text COLLATE pg_catalog."default",
    revision_requested_at timestamp with time zone,
    revision_by bigint,
    revision_by_username text COLLATE pg_catalog."default",
    revision_at timestamp with time zone,
    revision_returned_at timestamp with time zone,
    revision_completed_at timestamp with time zone,
    uid_hash text COLLATE pg_catalog."default",
    uid_enc text COLLATE pg_catalog."default",
    uid_last4 text COLLATE pg_catalog."default",
    CONSTRAINT uid_verification_requests_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.unreachable_users
(
    user_id bigint NOT NULL,
    reason text COLLATE pg_catalog."default" NOT NULL,
    last_seen timestamp without time zone NOT NULL DEFAULT now(),
    CONSTRAINT unreachable_users_pkey PRIMARY KEY (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_appeals
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    username text COLLATE pg_catalog."default",
    topic text COLLATE pg_catalog."default" NOT NULL,
    description text COLLATE pg_catalog."default" NOT NULL,
    participants text COLLATE pg_catalog."default",
    media_message_ids integer[] DEFAULT '{}'::integer[],
    origin_chat_id bigint NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'pending'::text,
    moderator_id bigint,
    moderator_username text COLLATE pg_catalog."default",
    moderator_comment text COLLATE pg_catalog."default",
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_appeals_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_bans
(
    id serial NOT NULL,
    user_id bigint NOT NULL,
    banned_until timestamp without time zone,
    reason character varying(255) COLLATE pg_catalog."default",
    issued_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT user_bans_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.user_preset_subscriptions
(
    id bigserial NOT NULL,
    user_id bigint NOT NULL,
    preset_id bigint NOT NULL,
    created_at timestamp with time zone NOT NULL DEFAULT now(),
    CONSTRAINT user_preset_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT user_preset_subscriptions_user_id_preset_id_key UNIQUE (user_id, preset_id)
);

CREATE TABLE IF NOT EXISTS public.user_subscriptions
(
    id serial NOT NULL,
    user_id bigint NOT NULL,
    card_id integer NOT NULL,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    last_confirmed_at timestamp with time zone,
    CONSTRAINT user_subscriptions_pkey PRIMARY KEY (id),
    CONSTRAINT ux_user_subscriptions UNIQUE (user_id, card_id)
);

CREATE TABLE IF NOT EXISTS public.user_uids
(
    uid text COLLATE pg_catalog."default" NOT NULL,
    user_id bigint NOT NULL,
    status text COLLATE pg_catalog."default" NOT NULL DEFAULT 'verified'::text,
    verified_at timestamp with time zone NOT NULL DEFAULT now(),
    verified_by bigint,
    updated_at timestamp with time zone NOT NULL DEFAULT now(),
    uid_hash text COLLATE pg_catalog."default",
    uid_enc text COLLATE pg_catalog."default",
    uid_last4 text COLLATE pg_catalog."default",
    CONSTRAINT user_uids_pkey PRIMARY KEY (uid),
    CONSTRAINT user_uids_user_id_key UNIQUE (user_id)
);

CREATE TABLE IF NOT EXISTS public.user_warnings
(
    id serial NOT NULL,
    user_id bigint NOT NULL,
    reason character varying(255) COLLATE pg_catalog."default",
    issued_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    details text COLLATE pg_catalog."default",
    CONSTRAINT user_warnings_pkey PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS public.users
(
    user_id bigint NOT NULL,
    username character varying(32) COLLATE pg_catalog."default",
    full_name character varying(255) COLLATE pg_catalog."default",
    is_subscribed boolean DEFAULT true,
    is_luxury boolean DEFAULT false,
    warnings_count integer DEFAULT 0,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_trusted boolean DEFAULT false,
    pm_opened boolean DEFAULT false,
    first_pm_at timestamp without time zone,
    last_pm_at timestamp without time zone,
    uid_verif_confirmed_count integer NOT NULL DEFAULT 0,
    uid_verif_rejected_count integer NOT NULL DEFAULT 0,
    uid_verif_last_confirmed_at timestamp with time zone,
    uid_verif_last_rejected_at timestamp with time zone,
    CONSTRAINT users_pkey PRIMARY KEY (user_id)
);

ALTER TABLE IF EXISTS public.admins
    ADD CONSTRAINT admins_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS admins_pkey
    ON public.admins(user_id);


ALTER TABLE IF EXISTS public.auction_owners
    ADD CONSTRAINT auction_owners_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_auction_owners_auction_id
    ON public.auction_owners(auction_id);


ALTER TABLE IF EXISTS public.auction_owners
    ADD CONSTRAINT auction_owners_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_auction_owners_user_id
    ON public.auction_owners(user_id);


ALTER TABLE IF EXISTS public.auction_posts_stats
    ADD CONSTRAINT auction_posts_stats_post_id_fkey FOREIGN KEY (post_id)
    REFERENCES public.auction_posts_backfill (post_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS auction_posts_stats_pkey
    ON public.auction_posts_stats(post_id);


ALTER TABLE IF EXISTS public.auctions
    ADD CONSTRAINT auctions_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;
CREATE INDEX IF NOT EXISTS idx_auctions_card_id
    ON public.auctions(card_id);


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT fk_audit_auction FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.audit_logs
    ADD CONSTRAINT fk_audit_user FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.autobid_actions
    ADD CONSTRAINT autobid_actions_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS autobid_actions_auction_id_idx
    ON public.autobid_actions(auction_id);


ALTER TABLE IF EXISTS public.autobid_actions
    ADD CONSTRAINT autobid_actions_autobid_id_fkey FOREIGN KEY (autobid_id)
    REFERENCES public.autobids (autobid_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.autobids
    ADD CONSTRAINT autobids_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bids_auction
    ON public.bids(auction_id);


ALTER TABLE IF EXISTS public.bids
    ADD CONSTRAINT bids_bidder_id_fkey FOREIGN KEY (bidder_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_bids_bidder
    ON public.bids(bidder_id);


ALTER TABLE IF EXISTS public.cards
    ADD CONSTRAINT cards_deck_id_fkey FOREIGN KEY (deck_id)
    REFERENCES public.decks (id) MATCH SIMPLE
    ON UPDATE CASCADE
    ON DELETE RESTRICT
    DEFERRABLE INITIALLY DEFERRED;


ALTER TABLE IF EXISTS public.delete_requests
    ADD CONSTRAINT delete_requests_lot_id_fkey FOREIGN KEY (lot_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.delete_requests
    ADD CONSTRAINT delete_requests_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.exchange_batches
    ADD CONSTRAINT exchange_batches_deck_id_fkey FOREIGN KEY (deck_id)
    REFERENCES public.decks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;
CREATE INDEX IF NOT EXISTS idx_exchange_batches_deck
    ON public.exchange_batches(deck_id);


ALTER TABLE IF EXISTS public.exchange_batches
    ADD CONSTRAINT exchange_batches_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.exchange_items
    ADD CONSTRAINT exchange_items_batch_id_fkey FOREIGN KEY (batch_id)
    REFERENCES public.exchange_batches (batch_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_exchange_items_batch
    ON public.exchange_items(batch_id);


ALTER TABLE IF EXISTS public.exchange_items
    ADD CONSTRAINT exchange_items_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.exchange_print_stats
    ADD CONSTRAINT exchange_print_stats_batch_id_fkey FOREIGN KEY (batch_id)
    REFERENCES public.exchange_batches (batch_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS exchange_print_stats_pkey
    ON public.exchange_print_stats(batch_id);


ALTER TABLE IF EXISTS public.market_listing_items
    ADD CONSTRAINT market_listing_items_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_market_listing_items_card
    ON public.market_listing_items(card_id);


ALTER TABLE IF EXISTS public.market_listing_items
    ADD CONSTRAINT market_listing_items_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES public.market_listings (listing_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_market_listing_items_listing
    ON public.market_listing_items(listing_id);


ALTER TABLE IF EXISTS public.market_listings
    ADD CONSTRAINT market_listings_deck_id_fkey FOREIGN KEY (deck_id)
    REFERENCES public.decks (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.market_listings
    ADD CONSTRAINT market_listings_seller_id_fkey FOREIGN KEY (seller_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.market_rate_tiers
    ADD CONSTRAINT market_rate_tiers_listing_id_fkey FOREIGN KEY (listing_id)
    REFERENCES public.market_listings (listing_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_market_rate_tiers_listing
    ON public.market_rate_tiers(listing_id);


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_auction_id_fkey FOREIGN KEY (auction_id)
    REFERENCES public.auctions (auction_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.notifications
    ADD CONSTRAINT notifications_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_notifications_user
    ON public.notifications(user_id);


ALTER TABLE IF EXISTS public.preset_aliases
    ADD CONSTRAINT preset_aliases_preset_id_fkey FOREIGN KEY (preset_id)
    REFERENCES public.presets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.settings
    ADD CONSTRAINT settings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS settings_pkey
    ON public.settings(user_id);


ALTER TABLE IF EXISTS public.uid_verification_confirmation_reminders
    ADD CONSTRAINT uid_verification_confirmation_reminders_conf_id_fkey FOREIGN KEY (conf_id)
    REFERENCES public.uid_verification_confirmations (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.uid_verification_confirmations
    ADD CONSTRAINT uid_verification_confirmations_counterparty_user_id_fkey FOREIGN KEY (counterparty_user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE SET NULL;


ALTER TABLE IF EXISTS public.uid_verification_confirmations
    ADD CONSTRAINT uid_verification_confirmations_request_id_fkey FOREIGN KEY (request_id)
    REFERENCES public.uid_verification_requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.uid_verification_events
    ADD CONSTRAINT uid_verification_events_request_id_fkey FOREIGN KEY (request_id)
    REFERENCES public.uid_verification_requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.uid_verification_request_reminders
    ADD CONSTRAINT uid_verification_request_reminders_request_id_fkey FOREIGN KEY (request_id)
    REFERENCES public.uid_verification_requests (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.uid_verification_requests
    ADD CONSTRAINT uid_verification_requests_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_bans
    ADD CONSTRAINT user_bans_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_preset_subscriptions
    ADD CONSTRAINT user_preset_subscriptions_preset_id_fkey FOREIGN KEY (preset_id)
    REFERENCES public.presets (id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;


ALTER TABLE IF EXISTS public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_card_id_fkey FOREIGN KEY (card_id)
    REFERENCES public.cards (card_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_card
    ON public.user_subscriptions(card_id);


ALTER TABLE IF EXISTS public.user_subscriptions
    ADD CONSTRAINT user_subscriptions_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS idx_user_subscriptions_user
    ON public.user_subscriptions(user_id);


ALTER TABLE IF EXISTS public.user_uids
    ADD CONSTRAINT user_uids_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;
CREATE INDEX IF NOT EXISTS user_uids_user_id_key
    ON public.user_uids(user_id);


ALTER TABLE IF EXISTS public.user_warnings
    ADD CONSTRAINT user_warnings_user_id_fkey FOREIGN KEY (user_id)
    REFERENCES public.users (user_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE CASCADE;

END;