#!/usr/bin/env bash
set -euo pipefail

output_dir="${1:-requirements}"
# Keep uv's autogenerated command header stable regardless of where CI wants
# the comparison copies. The committed locks were generated through this path.
work_dir="${LOCK_WORK_DIR:-/tmp/generated-locks}"
mkdir -p "$output_dir" "$work_dir"

for group in bot userbot tools dev; do
  generated_lock="$work_dir/$group.lock"
  uv pip compile \
    --python-version 3.13 \
    --generate-hashes \
    --no-emit-index-url \
    --output-file "$generated_lock" \
    "requirements/$group.in"

  if [[ "$output_dir/$group.lock" != "$generated_lock" ]]; then
    cp "$generated_lock" "$output_dir/$group.lock"
  fi
done
